// @agentforge/loom-core — public surface.
export * from "./types.js";
export * from "./addressing.js";
export * from "./identity.js";
export * from "./algebra.js";
// Leaf modules (merge/reapply, grant, determinism) are re-exported below once present.
export * from "./merge.js";
export * from "./reapply.js";
export * from "./grant.js";
export * from "./determinism.js";
export * from "./store.js";
export * from "./codec.js";
export * from "./blob.js";
export * from "./did.js";
export * from "./invariant-dsl.js";
export * from "./sandbox.js";
export * from "./lock.js";
export * from "./private.js";
export * from "./wire.js";
export * from "./wire-transport.js";
export * from "./proposal.js";
export * from "./materialize.js";
export * from "./admission.js";
export * from "./gc.js";
export * from "./sync.js";
export * from "./ledger.js";
export * from "./keys.js";
export * from "./revocation.js";
export * from "./session.js";
